/**
 * Where card-art bytes come from (1.9 lane D, S2; docs/plan-art-streaming.md
 * section 5). The art store (`artStore.ts`) asks a source for one file at a
 * time and decodes the Blob itself; everything about URLs, packs, HTTP ranges
 * and what to do when a host answers badly lives here.
 *
 * Two sources:
 * - **loose**: one `.webp` per key under `assets/art/cards/` and
 *   `assets/art/cards-half/`. The dev server and the desktop app read these
 *   (Tauri's asset protocol ignores `Range`, see docs/desktop-build.md).
 * - **packs**: one content-hashed `.bin` per set per tier under
 *   `assets/art/packs/`, written by `scripts/pack-art.ts`, read one card at a
 *   time by an HTTP range request. The offset index is bundled into the
 *   JavaScript, so the pack names and offsets always come from the same build.
 *
 * Which one a build uses is the `__ART_SOURCE__` define (vite.config.ts):
 * `'packs'` for a web production build, `'loose'` for dev, tests and Tauri.
 *
 * Phaser-free and store-free. The store codes against the `ArtSource` shape
 * and reads the rejection's `reason`: `'transient'` is what its retry (#432)
 * re-sends, `'failed'` is final for the session, `'aborted'` is its own
 * cancel. No retries happen in here.
 */

/** A file tier: the 640x800 files or the 320x400 ones. */
export type ArtFileTier = 'full' | 'half';

/** Why a read failed. The store's retry keys off this. */
export type ArtSourceFailure = 'transient' | 'failed' | 'aborted';

export class ArtSourceError extends Error {
  readonly reason: ArtSourceFailure;
  constructor(reason: ArtSourceFailure, message: string) {
    super(message);
    this.name = 'ArtSourceError';
    this.reason = reason;
  }
}

export interface ArtSource {
  readonly kind: 'loose' | 'packs';
  /**
   * One art file's bytes, as an `image/webp` Blob. A `half` read for a key
   * with no half file answers with the full file (as `artFileUrl` does).
   * Rejects only with an `ArtSourceError`.
   */
  read(key: string, tier: ArtFileTier, signal?: AbortSignal): Promise<Blob>;
}

// ── The pack index ────────────────────────────────────────────────────────────

/** Bumped when the index's shape changes; a mismatch falls back to loose files. */
export const PACK_INDEX_VERSION = 1;

/** `[packIndex, byteOffset, byteLength]` of one file inside a tier's packs. */
export type PackEntry = readonly [number, number, number];

export interface PackTierIndex {
  /** Pack file names, e.g. `full-base.1a2b3c4d5e.bin`, under `assets/art/packs/`. */
  packs: string[];
  /** Each pack's byte length, parallel to `packs`: the whole-pack length check. */
  sizes: number[];
  /** Parallel to the manifest's `cards`; `null` when this tier has no file for the key. */
  at: (PackEntry | null)[];
}

export interface PackIndex {
  version: number;
  /** `keysFingerprint(manifest.cards)` at pack time: guards the positional `at` lists. */
  keys: string;
  /** A tier that was not built (no `cards-half/` locally) is absent. */
  tiers: Partial<Record<ArtFileTier, PackTierIndex>>;
}

/**
 * FNV-1a (32-bit) over the keys joined by newlines, as 8 hex digits. The index
 * addresses keys by their position in the manifest, so a manifest regenerated
 * after the packs (a different file set on disk) must not be read against
 * them. Shared by the pack builder and the runtime; not a security hash.
 */
export function keysFingerprint(keys: readonly string[]): string {
  const text = keys.join('\n');
  let h = 0x811c9dc5;
  for (let i = 0; i < text.length; i++) {
    h ^= text.charCodeAt(i);
    h = Math.imul(h, 0x01000193) >>> 0;
  }
  return h.toString(16).padStart(8, '0');
}

/** True when the bytes start `RIFF????WEBP`: every entry in a pack does. */
export function isWebp(bytes: Uint8Array): boolean {
  return (
    bytes.length >= 12 &&
    bytes[0] === 0x52 && bytes[1] === 0x49 && bytes[2] === 0x46 && bytes[3] === 0x46 &&
    bytes[8] === 0x57 && bytes[9] === 0x45 && bytes[10] === 0x42 && bytes[11] === 0x50
  );
}

/**
 * The index generated by `scripts/pack-art.ts` into `src/data/art-packs.json`,
 * or null where it has not been built (dev, a fresh clone, tests). A glob, not
 * an import, so a checkout without the generated file still typechecks and runs.
 *
 * Null too in any build that reads loose files: the test is written on the
 * define itself, not through `buildArtSourceKind()`, so a `loose` build (dev,
 * Tauri) folds it to a constant and drops the glob, and with it the ~57 KiB
 * index, from the bundle.
 */
export function bundledPackIndex(): PackIndex | null {
  if (typeof __ART_SOURCE__ === 'undefined' || __ART_SOURCE__ !== 'packs') return null;
  const found = import.meta.glob<PackIndex>('../data/art-packs.json', { eager: true, import: 'default' });
  return Object.values(found)[0] ?? null;
}

declare const __ART_SOURCE__: 'loose' | 'packs' | undefined;

/** The source this build was made for (the `__ART_SOURCE__` define). */
export function buildArtSourceKind(): 'loose' | 'packs' {
  return typeof __ART_SOURCE__ !== 'undefined' && __ART_SOURCE__ === 'packs' ? 'packs' : 'loose';
}

// ── Shared plumbing ───────────────────────────────────────────────────────────

type FetchFn = (input: string, init?: RequestInit) => Promise<Response>;

export interface ArtSourceLog {
  warn(message: string): void;
  error(message: string): void;
}

interface Io {
  fetch: FetchFn;
  timeoutMs: number;
  log: ArtSourceLog;
}

/** A request that got an answer. `bytes` is null for a status without a body we read. */
interface Exchange {
  status: number;
  headers: Headers;
  bytes: Uint8Array | null;
  /** The status was 200 or 206 but reading the body threw (not an abort, not a timeout). */
  bodyFailed: boolean;
}

/**
 * How long a request may go without progress (no response yet, or no body
 * bytes since the last chunk) before it counts as transient. An idle limit,
 * not a total one, so a slow link can still finish a 38 MiB whole-pack
 * download while a stalled request never hangs the store.
 */
export const ART_FETCH_TIMEOUT_MS = 30_000;

const aborted = (what: string): ArtSourceError => new ArtSourceError('aborted', `${what}: aborted`);

/** Read a body chunk by chunk, calling `onChunk` after each (the idle timer's reset). */
async function readBody(res: Response, onChunk: () => void): Promise<Uint8Array> {
  if (!res.body) return new Uint8Array(await res.arrayBuffer());
  const reader = res.body.getReader();
  const chunks: Uint8Array[] = [];
  let total = 0;
  for (;;) {
    const { done, value } = await reader.read();
    if (done) break;
    chunks.push(value);
    total += value.length;
    onChunk();
  }
  if (chunks.length === 1) return chunks[0];
  const out = new Uint8Array(total);
  let at = 0;
  for (const chunk of chunks) {
    out.set(chunk, at);
    at += chunk.length;
  }
  return out;
}

/**
 * One GET, with the caller's abort and the idle timeout linked into it. Throws
 * `aborted` for the caller's cancel and `transient` for a network error or a
 * timeout; any HTTP answer comes back as an `Exchange`. The body is read only
 * for 200 and 206.
 */
async function exchange(io: Io, url: string, range: string | null, signal: AbortSignal | undefined): Promise<Exchange> {
  if (signal?.aborted) throw aborted(url);
  const ctl = new AbortController();
  let timedOut = false;
  const onAbort = (): void => ctl.abort();
  signal?.addEventListener('abort', onAbort, { once: true });
  let timer: ReturnType<typeof setTimeout> | undefined;
  const arm = (): void => {
    clearTimeout(timer);
    timer = setTimeout(() => {
      timedOut = true;
      ctl.abort();
    }, io.timeoutMs);
  };
  arm();
  const whyStopped = (fallback: string): ArtSourceError => {
    if (signal?.aborted) return aborted(url);
    return new ArtSourceError('transient', timedOut ? `${url}: timed out` : `${url}: ${fallback}`);
  };
  try {
    let res: Response;
    try {
      res = await io.fetch(url, { headers: range ? { Range: range } : undefined, signal: ctl.signal });
    } catch {
      throw whyStopped('network error');
    }
    if (res.status !== 200 && res.status !== 206) {
      res.body?.cancel().catch(() => undefined);
      return { status: res.status, headers: res.headers, bytes: null, bodyFailed: false };
    }
    arm();
    try {
      const bytes = await readBody(res, arm);
      return { status: res.status, headers: res.headers, bytes, bodyFailed: false };
    } catch {
      if (signal?.aborted || timedOut) throw whyStopped('body read failed');
      return { status: res.status, headers: res.headers, bytes: null, bodyFailed: true };
    }
  } finally {
    clearTimeout(timer);
    signal?.removeEventListener('abort', onAbort);
  }
}

/** 408, 429 and 5xx are worth another try; any other error status is not. */
function statusFailure(status: number): ArtSourceFailure {
  return status === 408 || status === 429 || status >= 500 ? 'transient' : 'failed';
}

const webpBlob = (bytes: Uint8Array<ArrayBuffer>): Blob => new Blob([bytes], { type: 'image/webp' });

// ── The loose source ──────────────────────────────────────────────────────────

export interface LooseSourceOpts {
  fetch?: FetchFn;
  /** URL prefix of the art folders; relative to the page, as the game's base is `./`. */
  base?: string;
  /** Which keys have a half file (default: the manifest's `half` list). */
  hasHalf?: (key: string) => boolean;
  timeoutMs?: number;
  log?: ArtSourceLog;
}

/** The loose file's URL for a key: the same rule as `artFileUrl`. */
export function looseArtUrl(key: string, tier: ArtFileTier, hasHalf: (key: string) => boolean, base = 'assets/art/'): string {
  const dir = tier === 'half' && hasHalf(key) ? 'cards-half' : 'cards';
  return `${base}${dir}/${key}.webp`;
}

interface ManifestLists {
  cards: readonly string[];
  half: ReadonlySet<string>;
}
let manifestLists: ManifestLists | null = null;

/**
 * The generated art manifest's `cards` and `half`, read through a glob so this
 * module has no static JSON import: `scripts/pack-art.ts` (and through it
 * vite.config.ts) imports this file and must load where the manifest has not
 * been generated yet. Only ever called at read time, inside the game bundle.
 */
function bundledManifest(): ManifestLists {
  if (!manifestLists) {
    const found = import.meta.glob<{ cards?: string[]; half?: string[] }>('../data/art-manifest.json', {
      eager: true,
      import: 'default',
    });
    const m = Object.values(found)[0];
    manifestLists = { cards: m?.cards ?? [], half: new Set(m?.half ?? []) };
  }
  return manifestLists;
}

export function createLooseSource(opts: LooseSourceOpts = {}): ArtSource {
  const io: Io = {
    fetch: opts.fetch ?? ((input, init) => fetch(input, init)),
    timeoutMs: opts.timeoutMs ?? ART_FETCH_TIMEOUT_MS,
    log: opts.log ?? console,
  };
  const hasHalf = opts.hasHalf ?? ((key: string) => bundledManifest().half.has(key));
  const base = opts.base ?? 'assets/art/';
  const failed = new Set<string>();
  return {
    kind: 'loose',
    async read(key, tier, signal) {
      const url = looseArtUrl(key, tier, hasHalf, base);
      if (failed.has(url)) throw new ArtSourceError('failed', `${url}: failed earlier this session`);
      const ex = await exchange(io, url, null, signal);
      if (ex.bytes !== null && isWebp(ex.bytes)) return webpBlob(ex.bytes as Uint8Array<ArrayBuffer>);
      if (ex.bodyFailed) throw new ArtSourceError('transient', `${url}: body read failed`);
      const reason = ex.bytes !== null ? 'failed' : statusFailure(ex.status);
      if (reason === 'failed') failed.add(url);
      throw new ArtSourceError(reason, ex.bytes !== null ? `${url}: not a webp file` : `${url}: HTTP ${ex.status}`);
    },
  };
}

// ── The pack source ───────────────────────────────────────────────────────────

/** Whole-pack mode holds at most this many packs' bytes (least recently used dropped). */
export const WHOLE_PACKS_HELD = 2;

type PackMode =
  /** Not asked yet this session: the next read goes alone and decides. */
  | 'unknown'
  /** Ranges work: read each card with its own range request, in parallel. */
  | 'range'
  /** The host ignores or garbles ranges: download the pack once and slice it. */
  | 'whole'
  /** The pack is gone (a tab older than the deploy) or unusable: read loose files. */
  | 'loose';

interface PackState {
  name: string;
  size: number;
  mode: PackMode;
  /**
   * Resolves (never rejects) when the read that is deciding this pack's mode
   * settles: with `'transient'` when it failed that way, else null.
   */
  deciding: Promise<DecideOutcome> | null;
  whole: Uint8Array | null;
  warned: boolean;
  errored: boolean;
}

/** How a deciding read ended, for the reads that waited on it. */
type DecideOutcome = 'transient' | null;

interface Located {
  tier: ArtFileTier;
  pack: PackState;
  offset: number;
  length: number;
}

export interface PackSourceOpts {
  index: PackIndex;
  /** The manifest's `cards`, the order `at` is parallel to. */
  keys?: readonly string[];
  /** Where a pack's keys go when the pack is missing or unusable. */
  loose?: ArtSource;
  fetch?: FetchFn;
  /** URL prefix of the packs folder. */
  base?: string;
  timeoutMs?: number;
  log?: ArtSourceLog;
}

/** Parses `bytes <start>-<end>/<total|*>`; null when absent or malformed. */
export function parseContentRange(header: string | null): { start: number; end: number } | null {
  const m = header ? /^bytes (\d+)-(\d+)\/(\d+|\*)$/.exec(header.trim()) : null;
  return m ? { start: Number(m[1]), end: Number(m[2]) } : null;
}

/** Any `Content-Encoding` other than `identity` means the host compressed the pack. */
function isEncoded(headers: Headers): boolean {
  const enc = headers.get('content-encoding');
  return enc !== null && enc.trim() !== '' && enc.trim().toLowerCase() !== 'identity';
}

function waitFor<T>(p: Promise<T>, signal: AbortSignal | undefined, what: string): Promise<T> {
  if (!signal) return p;
  if (signal.aborted) return Promise.reject(aborted(what));
  return new Promise<T>((resolve, reject) => {
    const onAbort = (): void => reject(aborted(what));
    signal.addEventListener('abort', onAbort, { once: true });
    void p.then((value) => {
      signal.removeEventListener('abort', onAbort);
      resolve(value);
    });
  });
}

export function createPackSource(opts: PackSourceOpts): ArtSource {
  const io: Io = {
    fetch: opts.fetch ?? ((input, init) => fetch(input, init)),
    timeoutMs: opts.timeoutMs ?? ART_FETCH_TIMEOUT_MS,
    log: opts.log ?? console,
  };
  const keys = opts.keys ?? bundledManifest().cards;
  const loose = opts.loose ?? createLooseSource({ fetch: io.fetch, timeoutMs: io.timeoutMs, log: io.log });
  const base = opts.base ?? 'assets/art/packs/';
  const position = new Map<string, number>();
  keys.forEach((key, i) => position.set(key, i));

  const states = new Map<string, PackState>();
  const stateFor = (name: string, size: number): PackState => {
    let st = states.get(name);
    if (!st) {
      st = { name, size, mode: 'unknown', deciding: null, whole: null, warned: false, errored: false };
      states.set(name, st);
    }
    return st;
  };
  /** Packs holding their whole bytes, least recently used first. */
  const held: PackState[] = [];
  const failed = new Set<string>();

  const warnOnce = (st: PackState, message: string): void => {
    if (st.warned) return;
    st.warned = true;
    io.log.warn(`art packs: ${st.name}: ${message}`);
  };
  const errorOnce = (st: PackState, message: string): void => {
    if (st.errored) return;
    st.errored = true;
    io.log.error(`art packs: ${st.name}: ${message}`);
  };
  const failKey = (loc: Located, key: string, message: string): ArtSourceError => {
    failed.add(`${loc.tier}:${key}`);
    errorOnce(loc.pack, message);
    return new ArtSourceError('failed', `${key} (${loc.tier}): ${message}`);
  };

  /** The entry to read for (key, tier): a half read with no half file reads the full one. */
  const locate = (key: string, tier: ArtFileTier): Located | null => {
    const i = position.get(key);
    if (i === undefined) return null;
    const order: ArtFileTier[] = tier === 'half' ? ['half', 'full'] : ['full'];
    for (const t of order) {
      const tierIndex = opts.index.tiers[t];
      const entry = tierIndex?.at[i];
      if (!tierIndex || !entry) continue;
      const [p, offset, length] = entry;
      return { tier: t, pack: stateFor(tierIndex.packs[p], tierIndex.sizes[p]), offset, length };
    }
    return null;
  };

  const hold = (st: PackState, bytes: Uint8Array): void => {
    st.whole = bytes;
    const at = held.indexOf(st);
    if (at >= 0) held.splice(at, 1);
    held.push(st);
    while (held.length > WHOLE_PACKS_HELD) {
      const dropped = held.shift()!;
      dropped.whole = null;
    }
  };

  const slice = (loc: Located, key: string, bytes: Uint8Array): Blob => {
    const end = loc.offset + loc.length;
    const part = end <= bytes.length ? bytes.subarray(loc.offset, end) : null;
    if (!part || !isWebp(part)) throw failKey(loc, key, `entry for ${key} is not a webp file inside the pack`);
    return webpBlob(part as Uint8Array<ArrayBuffer>);
  };

  /** A whole pack body arrived: keep it if its length is right, else read loose files. */
  const acceptWhole = (st: PackState, bytes: Uint8Array): void => {
    if (bytes.length !== st.size) {
      errorOnce(st, `whole pack is ${bytes.length} bytes, the index says ${st.size}; reading loose files`);
      st.mode = 'loose';
      return;
    }
    hold(st, bytes);
  };

  const toLoose = (st: PackState): void => {
    st.mode = 'loose';
    warnOnce(st, 'pack not found (a tab older than the deploy?); reading loose files');
  };

  const toWhole = (st: PackState, why: string): void => {
    st.mode = 'whole';
    warnOnce(st, `${why}; downloading the whole pack once and reading from it`);
  };

  /**
   * One range read. Answers the key's Blob, or null when the answer changed
   * the pack's mode and the caller should look again.
   */
  const readRange = async (loc: Located, key: string, signal: AbortSignal | undefined): Promise<Blob | null> => {
    const st = loc.pack;
    const url = `${base}${st.name}`;
    const ex = await exchange(io, url, `bytes=${loc.offset}-${loc.offset + loc.length - 1}`, signal);
    if (ex.status === 404) {
      toLoose(st);
      return null;
    }
    if (ex.status === 416) {
      st.mode = 'range';
      throw failKey(loc, key, `416 for ${key}'s range: the index and the pack disagree`);
    }
    if (ex.status !== 200 && ex.status !== 206) {
      throw new ArtSourceError(statusFailure(ex.status), `${url}: HTTP ${ex.status}`);
    }
    if (isEncoded(ex.headers)) {
      // The host compressed the pack, so any range addressed compressed bytes.
      // A full 200 body is still good: fetch decompressed it.
      toWhole(st, `served with Content-Encoding ${ex.headers.get('content-encoding')}`);
      if (ex.status === 200 && ex.bytes) acceptWhole(st, ex.bytes);
      return null;
    }
    if (ex.bodyFailed) {
      // Not encoded (that case returned above), so the body stopped because
      // the link dropped: transient. A 200 still says the host ignores Range.
      if (ex.status === 200) st.mode = 'whole';
      throw new ArtSourceError('transient', `${url}: the body failed to read`);
    }
    const bytes = ex.bytes!;
    if (ex.status === 200) {
      toWhole(st, 'the host ignored Range and sent the whole pack');
      acceptWhole(st, bytes);
      return null;
    }
    const cr = parseContentRange(ex.headers.get('content-range'));
    if (!cr || cr.start !== loc.offset || bytes.length !== loc.length || !isWebp(bytes)) {
      if (st.mode === 'unknown') st.mode = 'range';
      throw failKey(loc, key, `the range for ${key} came back wrong (length ${bytes.length}, want ${loc.length})`);
    }
    if (st.mode === 'unknown') st.mode = 'range';
    return webpBlob(bytes as Uint8Array<ArrayBuffer>);
  };

  /** Download the whole pack (whole-pack mode with nothing held). */
  const readWhole = async (st: PackState, signal: AbortSignal | undefined): Promise<void> => {
    const url = `${base}${st.name}`;
    const ex = await exchange(io, url, null, signal);
    if (ex.status === 404) return toLoose(st);
    if (ex.bodyFailed) throw new ArtSourceError('transient', `${url}: the whole-pack body failed to read`);
    if (ex.bytes === null) throw new ArtSourceError(statusFailure(ex.status), `${url}: HTTP ${ex.status}`);
    acceptWhole(st, ex.bytes);
  };

  return {
    kind: 'packs',
    async read(key, tier, signal) {
      const loc = locate(key, tier);
      if (!loc) {
        // Not in the index (not in the manifest, or a tier the packs lack a
        // file for): the loose file is the only place it could be.
        return loose.read(key, tier, signal);
      }
      if (failed.has(`${loc.tier}:${key}`)) {
        throw new ArtSourceError('failed', `${key} (${loc.tier}): failed earlier this session`);
      }
      const st = loc.pack;
      for (;;) {
        if (st.mode === 'loose') return loose.read(key, loc.tier, signal);
        if (st.mode === 'whole' && st.whole) {
          hold(st, st.whole);
          return slice(loc, key, st.whole);
        }
        if (st.deciding) {
          const outcome = await waitFor(st.deciding, signal, key);
          // The read we waited on failed transiently and settled nothing: do
          // not re-decide one at a time (each with its own idle timeout) on a
          // link that just stalled. Fail too; the store's retry re-sends.
          if (outcome === 'transient' && (st.mode === 'unknown' || (st.mode === 'whole' && !st.whole))) {
            throw new ArtSourceError('transient', `${key}: the read deciding ${st.name} failed`);
          }
          continue;
        }
        if (st.mode === 'range') {
          const blob = await readRange(loc, key, signal);
          if (blob) return blob;
          continue;
        }
        // 'unknown', or 'whole' with nothing held: this read goes alone and the
        // pack's other reads wait for its answer, so a host that ignores ranges
        // sends the pack once, not six times.
        let settle!: (outcome: DecideOutcome) => void;
        let outcome: DecideOutcome = null;
        st.deciding = new Promise<DecideOutcome>((resolve) => (settle = resolve));
        try {
          if (st.mode === 'whole') {
            await readWhole(st, signal);
          } else {
            const blob = await readRange(loc, key, signal);
            if (blob) return blob;
          }
        } catch (err) {
          if (err instanceof ArtSourceError && err.reason === 'transient') outcome = 'transient';
          throw err;
        } finally {
          st.deciding = null;
          settle(outcome);
        }
      }
    },
  };
}

// ── The build's choice ────────────────────────────────────────────────────────

export interface ArtSourceOpts {
  /** Default: the build's `__ART_SOURCE__`. */
  kind?: 'loose' | 'packs';
  /** Default: the bundled index. `null` forces loose files. */
  index?: PackIndex | null;
  keys?: readonly string[];
  hasHalf?: (key: string) => boolean;
  fetch?: FetchFn;
  timeoutMs?: number;
  log?: ArtSourceLog;
}

/**
 * The source for this build: packs when the build made them and its index
 * matches the manifest, loose files otherwise (dev, the desktop app, a local
 * build that never packed, an index from a different manifest).
 */
export function createArtSource(opts: ArtSourceOpts = {}): ArtSource {
  const log = opts.log ?? console;
  const loose = createLooseSource({ fetch: opts.fetch, hasHalf: opts.hasHalf, timeoutMs: opts.timeoutMs, log });
  if ((opts.kind ?? buildArtSourceKind()) === 'loose') return loose;
  const index = opts.index === undefined ? bundledPackIndex() : opts.index;
  if (!index) return loose;
  const keys = opts.keys ?? bundledManifest().cards;
  if (index.version !== PACK_INDEX_VERSION || index.keys !== keysFingerprint(keys)) {
    log.error('art packs: the pack index does not match this build\'s art manifest; reading loose files');
    return loose;
  }
  return createPackSource({ index, keys, loose, fetch: opts.fetch, timeoutMs: opts.timeoutMs, log });
}
