import type { CardDb, Permanent, PlayerId } from '../src/engine/types';
import { TEST_DB } from './helpers';

/** Test-only Sands of the Duat cards. No fixture below enters the shipped catalog. */
export const DUAT_DB: CardDb = {
  ...TEST_DB,
  'du-rite-one': {
    id: 'du-rite-one',
    name: 'Duat Rite One',
    types: ['creature'],
    subtypes: ['God'],
    cost: { generic: 1, pips: {} },
    colors: ['B'],
    attack: 5,
    defense: 5,
    rite: { n: 1 },
    rarity: 'c',
  },
  'du-rite-two': {
    id: 'du-rite-two',
    name: 'Duat Rite Two',
    types: ['creature'],
    subtypes: ['God'],
    cost: { generic: 1, pips: {} },
    colors: ['B'],
    attack: 7,
    defense: 6,
    rite: { n: 2 },
    rarity: 'r',
  },
  'du-rite-empowered': {
    id: 'du-rite-empowered',
    name: 'Duat Empowered Rite',
    types: ['creature'],
    subtypes: ['God'],
    cost: { generic: 1, pips: {} },
    colors: ['B'],
    attack: 4,
    defense: 4,
    rite: { n: 1 },
    empower: { cost: { generic: 0, pips: {} }, ops: [{ op: 'gainLife', n: 1 }] },
    rarity: 'r',
  },
  'du-nine-lives': {
    id: 'du-nine-lives',
    name: 'Duat Nine Lives',
    types: ['creature'],
    subtypes: ['Cat'],
    cost: { generic: 0, pips: {} },
    colors: ['B'],
    attack: 2,
    defense: 2,
    nineLives: true,
    rarity: 'c',
  },
  'du-nine-vanilla': {
    id: 'du-nine-vanilla',
    name: 'Duat Nine Lives Baseline',
    types: ['creature'],
    subtypes: ['Cat'],
    cost: { generic: 0, pips: {} },
    colors: ['B'],
    attack: 2,
    defense: 2,
    rarity: 'c',
  },
  'du-nine-rider': {
    id: 'du-nine-rider',
    name: 'Duat Nine Lives Rider',
    types: ['creature'],
    subtypes: ['Cat'],
    cost: { generic: 0, pips: {} },
    colors: ['B'],
    attack: 2,
    defense: 2,
    nineLives: true,
    abilities: [
      { when: 'arrives', ops: [{ op: 'gainLife', n: 1 }] },
      { when: 'dies', ops: [{ op: 'loseLife', n: 1, who: 'opponent' }] },
    ],
    rarity: 'r',
  },
  'du-nine-full': {
    id: 'du-nine-full',
    name: 'Duat Crowded Nine Lives',
    types: ['creature'],
    subtypes: ['Cat'],
    cost: { generic: 0, pips: {} },
    colors: ['B'],
    attack: 1,
    defense: 1,
    nineLives: true,
    abilities: [{ when: 'dies', ops: [{ op: 'createToken', token: 'du-scarab-token', count: 1 }] }],
    rarity: 'r',
  },
  'du-nine-token': {
    id: 'du-nine-token',
    name: 'Duat Nine Lives Token',
    types: ['creature'],
    subtypes: ['Cat'],
    cost: { generic: 0, pips: {} },
    colors: ['B'],
    attack: 1,
    defense: 1,
    nineLives: true,
    token: true,
    rarity: 'c',
  },
  'du-nine-artifact': {
    id: 'du-nine-artifact',
    name: 'Duat Nine Lives Idol',
    types: ['creature', 'artifact'],
    subtypes: ['Cat'],
    cost: { generic: 0, pips: {} },
    colors: ['B'],
    attack: 1,
    defense: 1,
    nineLives: true,
    rarity: 'r',
  },
  'du-nine-quest': {
    id: 'du-nine-quest',
    name: 'Duat Nine Lives Quest',
    types: ['creature'],
    subtypes: ['Cat'],
    cost: { generic: 0, pips: {} },
    colors: ['B'],
    attack: 1,
    defense: 1,
    nineLives: true,
    chapters: [[], []],
    rarity: 'r',
  },
  'du-fodder-spawn': {
    id: 'du-fodder-spawn',
    name: 'Duat Returning Fodder',
    types: ['creature'],
    subtypes: ['Scarab'],
    cost: { generic: 0, pips: {} },
    colors: ['B'],
    attack: 0,
    defense: 1,
    abilities: [{ when: 'dies', ops: [{ op: 'createToken', token: 'du-scarab-token', count: 1 }] }],
    rarity: 'c',
  },
  'du-double-spawn': {
    id: 'du-double-spawn',
    name: 'Duat Double Fodder',
    types: ['creature'],
    subtypes: ['Scarab'],
    cost: { generic: 0, pips: {} },
    colors: ['B'],
    attack: 0,
    defense: 1,
    abilities: [{ when: 'dies', ops: [{ op: 'createToken', token: 'du-scarab-token', count: 2 }] }],
    rarity: 'c',
  },
  'du-order-fodder': {
    id: 'du-order-fodder',
    name: 'Duat Ordered Fodder',
    types: ['creature'],
    subtypes: ['Scarab'],
    cost: { generic: 0, pips: {} },
    colors: ['B'],
    attack: 0,
    defense: 1,
    abilities: [{ when: 'dies', ops: [{ op: 'loseLife', n: 1, who: 'opponent' }] }],
    rarity: 'c',
  },
  'du-raise-fodder': {
    id: 'du-raise-fodder',
    name: 'Duat Raising Fodder',
    types: ['creature'],
    subtypes: ['Jackal'],
    cost: { generic: 0, pips: {} },
    colors: ['B'],
    attack: 0,
    defense: 1,
    abilities: [{ when: 'dies', ops: [{ op: 'raise', to: 'top' }] }],
    rarity: 'c',
  },
  'du-cheap-fodder': {
    id: 'du-cheap-fodder',
    name: 'Duat Cheap Fodder',
    types: ['creature'],
    subtypes: ['Scarab'],
    cost: { generic: 0, pips: {} },
    colors: ['B'],
    attack: 0,
    defense: 1,
    rarity: 'c',
  },
  'du-mid-body': {
    id: 'du-mid-body',
    name: 'Duat Mid Body',
    types: ['creature'],
    subtypes: ['Jackal'],
    cost: { generic: 2, pips: {} },
    colors: ['B'],
    attack: 2,
    defense: 2,
    rarity: 'c',
  },
  'du-mid-payoff': {
    id: 'du-mid-payoff',
    name: 'Duat Mid Payoff',
    types: ['creature'],
    subtypes: ['Jackal'],
    cost: { generic: 2, pips: {} },
    colors: ['B'],
    attack: 2,
    defense: 2,
    abilities: [{ when: 'dies', ops: [{ op: 'createToken', token: 'du-scarab-token', count: 3 }] }],
    rarity: 'c',
  },
  'du-modest-cast': {
    id: 'du-modest-cast',
    name: 'Duat Modest Cast',
    types: ['creature'],
    subtypes: ['Jackal'],
    cost: { generic: 1, pips: {} },
    colors: ['B'],
    attack: 2,
    defense: 2,
    rarity: 'c',
  },
  'du-best-body': {
    id: 'du-best-body',
    name: 'Duat Best Body',
    types: ['creature'],
    subtypes: ['God'],
    cost: { generic: 6, pips: {} },
    colors: ['B'],
    attack: 6,
    defense: 6,
    rarity: 'r',
  },
  'du-relic': {
    id: 'du-relic',
    name: 'Duat Relic',
    types: ['artifact'],
    subtypes: [],
    cost: { generic: 0, pips: {} },
    colors: [],
    rarity: 'c',
  },
  'du-counter': {
    id: 'du-counter',
    name: 'Duat Denial',
    types: ['charm'],
    subtypes: [],
    cost: { generic: 0, pips: {} },
    colors: [],
    abilities: [{ when: 'spell', targets: [{ what: 'spell' }], ops: [{ op: 'cancel', to: 'target' }] }],
    rarity: 'c',
  },
  'du-scarab-token': {
    id: 'du-scarab-token',
    name: 'Duat Scarab',
    types: ['creature'],
    subtypes: ['Scarab'],
    cost: { generic: 0, pips: {} },
    colors: ['B'],
    attack: 1,
    defense: 1,
    token: true,
    rarity: 'c',
  },
};

export function duatPermanent(
  iid: number,
  cardId: string,
  controller: PlayerId = 0,
): Permanent {
  return {
    iid,
    instanceId: iid,
    cardId,
    owner: controller,
    controller,
    tapped: false,
    enteredThisTurn: false,
    damage: 0,
    deathtouched: false,
    attachments: [],
    plusOneCounters: 0,
    untilEotMods: [],
  };
}
