import type { CardDb } from '../src/engine/types';
import { TEST_DB } from './helpers';

/** Test-only carriers and removal spells. No Hauntlink card ships in CARD_DB. */
export const HAUNTLINK_DB: CardDb = {
  ...TEST_DB,
  free_host: {
    id: 'free_host',
    name: 'Signal Host',
    types: ['creature'],
    subtypes: [],
    cost: { generic: 0, pips: {} },
    colors: [],
    attack: 2,
    defense: 2,
    rarity: 'c',
  },
  hauntlink_artifact: {
    id: 'hauntlink_artifact',
    name: 'Signal Reliquary',
    types: ['artifact'],
    subtypes: [],
    cost: { generic: 0, pips: {} },
    colors: [],
    hauntlink: {
      cost: { generic: 0, pips: {} },
      linked: { p: 1, t: 1, grantKeywords: ['skyborne'] },
    },
    abilities: [{ when: 'arrives', ops: [{ op: 'draw', n: 1 }] }],
    rarity: 'c',
  },
  hauntlink_enchantment: {
    id: 'hauntlink_enchantment',
    name: 'Possession Lattice',
    types: ['enchantment'],
    subtypes: [],
    cost: { generic: 0, pips: {} },
    colors: [],
    hauntlink: { cost: { generic: 0, pips: {} }, linked: { t: 1 } },
    rarity: 'c',
  },
  priced_hauntlink_artifact: {
    id: 'priced_hauntlink_artifact',
    name: 'Priced Signal Reliquary',
    types: ['artifact'],
    subtypes: [],
    cost: { generic: 5, pips: {} },
    colors: [],
    hauntlink: {
      cost: { generic: 2, pips: {} },
      linked: { p: 1 },
    },
    rarity: 'c',
  },
  keyword_link: {
    id: 'keyword_link',
    name: 'Skyline Relay',
    types: ['artifact'],
    subtypes: [],
    cost: { generic: 0, pips: {} },
    colors: [],
    hauntlink: { cost: { generic: 0, pips: {} }, linked: { grantKeywords: ['skyborne'] } },
    rarity: 'c',
  },
  ordinary_artifact: {
    id: 'ordinary_artifact',
    name: 'Standalone Relic',
    types: ['artifact'],
    subtypes: [],
    cost: { generic: 0, pips: {} },
    colors: [],
    rarity: 'c',
  },
  destroy_creature: {
    id: 'destroy_creature',
    name: 'Host Breaker',
    types: ['charm'],
    subtypes: [],
    cost: { generic: 0, pips: {} },
    colors: [],
    abilities: [{ when: 'spell', targets: [{ what: 'creature' }], ops: [{ op: 'destroy', to: 'target' }] }],
    rarity: 'c',
  },
  recall_creature: {
    id: 'recall_creature',
    name: 'Host Recall',
    types: ['charm'],
    subtypes: [],
    cost: { generic: 0, pips: {} },
    colors: [],
    abilities: [{ when: 'spell', targets: [{ what: 'creature' }], ops: [{ op: 'recall', to: 'target' }] }],
    rarity: 'c',
  },
  sever_creature: {
    id: 'sever_creature',
    name: 'Host Sever',
    types: ['charm'],
    subtypes: [],
    cost: { generic: 0, pips: {} },
    colors: [],
    abilities: [{ when: 'spell', targets: [{ what: 'creature' }], ops: [{ op: 'sever', to: 'target' }] }],
    rarity: 'c',
  },
  creature_sweep: {
    id: 'creature_sweep',
    name: 'Creature Sweep',
    types: ['ritual'],
    subtypes: [],
    cost: { generic: 0, pips: {} },
    colors: [],
    abilities: [{ when: 'spell', ops: [{ op: 'massDestroy', filter: 'allCreatures' }] }],
    rarity: 'c',
  },
  enchantment_sweep: {
    id: 'enchantment_sweep',
    name: 'Enchantment Sweep',
    types: ['ritual'],
    subtypes: [],
    cost: { generic: 0, pips: {} },
    colors: [],
    abilities: [{ when: 'spell', ops: [{ op: 'massDestroy', filter: 'allEnchantments' }] }],
    rarity: 'c',
  },
};
